[package]
name = "iot-nano-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autobins = false

[dependencies]
argon2.workspace = true
aes-gcm.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
iot-nano-foundation = { path = "../../crates/iot-nano-foundation" }
iot-storage = { path = "../../crates/iot-storage" }
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
tower.workspace = true

[lib]
name = "iot_api"
